name: icka

on:
  schedule:
    - cron: '0 * * * *'
  repository_dispatch:
      
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: 
      - run: make
      - run: make install

      - name: icka
        env:
          ICKA_EMAIL: ${{ secrets.ICKA_EMAIL }}
          ICKA_PASSWORD: ${{ secrets.ICKA_PASSWORD }}
        run: icka
